name: Foundry CI

on:
  push:
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.0.10
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test
        id: test

      - name: Run snapshot
        run: |
          forge snapshot
        id: snapshot
